apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  jwt-secret-key: "your-super-secret-key-that-is-long-and-random"
  mongo-uri: "mongodb://admin:password123@mongodb-service:27017/much_todo_db?authSource=admin"
